### ISSUE TITLE
Option for debug port with clj bash script

### ISSUE THREAD

**Issue by kzar** [citizen428/ClojureX#1]
ClojureX helped me get up and running really fast but I had one problem. I needed to get clojure running with the debug port open. In the end I botched the clj script to add the -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8888 argument.

I thought maybe we should add a --debug-port switch to the cjl script. I'm not sure how GitHub works but I don't mind learning about it and making the change if I have permission.

Cheers, Dave.

**Comment by citizen428** [comment]
GitHub is easy:
- fork
- checkout from your private URL
- apply changes and commit
- send me a pull request

I'm kinda busy right now, so if you have time to look into that, I'd much appreciate it.

Thanks!

**Comment by citizen428** [comment]
Merged and pushed Dave's change.
