### ISSUE TITLE
Bad CPU type

### ISSUE THREAD

**Issue by timsears** [citizen428/ClojureX#2]
clj: line 32: /System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home/bin/java: Bad CPU type in executable

Is this an issue with 1.5 versus 1.6? I am running osx 10.5.8 and cannot upgrade to 1.6
-T

**Comment by citizen428** [comment]
I only have Snow Leopard available now, but I started ClojureX on 10.5. If you find anything out, please let me know!

**Comment by citizen428** [comment]
I did a bit of research on this, quite a few people seem to have this problem with 1.6...

Regarding "I am running osx 10.5.8 and cannot upgrade to 1.6": judging from the output you posted, you did already upgrade to 1.6.

"This release of J2SE 5.0 and J2SE 1.4.2 supports all Intel and PowerPC-based Macs. Java SE 6 is available on 64-bit, Intel-based Macs only."
http://support.apple.com/kb/HT2733

**Comment by timsears** [comment]
I think my old chip/java 1.6/and mac osx do not mix for some reason. I have a similar issue with another java app called Quantrix. This is Apple's way of selling me a new computer!
