### ISSUE TITLE
TextMate support not working

### ISSUE THREAD

**Issue by neuwirthe** [citizen428/ClojureX#3]
Textmate support seems to work for file editing, but when I try cmd-R 
the build and run dialog tells me that this is not a valid xcode project.
What do I need to change?

**Comment by citizen428** [comment]
I'm not using the Textmate support myself, I mostly install it because I want to be nice. If you find out more and fix this issue, I'll include the fix, but I don't think I'll have time to look into it myself anytime soon.

**Comment by citizen428** [comment]
Tried again with a newer version of the bundle (change to a different fork) and Cmd-R works for me. I'll close this issue.
