### ISSUE TITLE
Slime-repl not working in Aquamacs

### ISSUE THREAD

**Issue by jeffthink** [citizen428/ClojureX#4]
Installed ClojureX and ran ./configure_emacs to set up my .emacs file.  Loading up Aquamacs, and calling M-x slime brings up a slime-repl window as it should, but attempting to evaluate any code in the repl doesn't work.  Basically, the return key to evaluate an expression (e.g. (+ 2 2)) causes cursor to move down a line instead of evaluating the current line.  This same process works no problem in carbon emacs.  This same thing also happened when using leiningen and lein swank, then M-x slime-connect to get access to the slime repl.

Honestly, I'm not sure if ClojureX is part of the problem.  I can't get slime-repl to work via any clojure install method in aquamacs.  Perhaps there's a missing config statement in .emacs?  Any help is much appreciated.

**Comment by citizen428** [comment]
I'm a bit clueless here, while I still used Aquamacs it always worked for me.

**Comment by jeffthink** [comment]
no problem - like I said, good chance it's not even your configuration...just that I searched all over to find someone with similar problem and coundn't so figured I'd ask someone I knew had same config.  Will just use carbon emacs until I get it figured out.  Thanks for the project!

**Comment by citizen428** [comment]
Emacs config not part of ClojureX anymore => closing.
